name: Docker Image CI

env:
  AZURE_WEBAPP_NAME: pleyapi

on:
  push:
    branches: 
      - main
        dev
        feat*
  pull_request:
    branches: 
      - main
        dev
        feat*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone the Repo
      uses: actions/checkout@v4

    - name: Install Docker Using Buildx
      uses: docker/setup-buildx-action@v3.8.0

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.LP_DOCKER_USER }}
        password: ${{ secrets.LP_DOCKER_PASS }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v6.11.0
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: index.docker.io/lypark5/pleyimage:latest, index.docker.io/lypark5/pleyimage:${{ github.sha }} 